### ISSUE TITLE
Make field `nullable` when backend does not require it to be `@NotNull` or `@NotBlank`

### ISSUE THREAD

**Issue by nkescec** [croz-ltd/nrich-demo-frontend#28]
## Basic information

* nrich-demo-frontend version: 0.0.3 (only nrich/form-configuration-core is used)
  
* Module: nrich-form-configuration
  

## Additional information

yup version: 0.28.5

## Enhancement description

When backend validation does not specify that field has to be `@NotNull` or `@NotBlank` then include `.nullable()` when generating yup schema for that field. 

### Current behaviour

Current behaviour is that the generated yup schemas expect that every field is not nullable, which is quite problematic when these fields can actually be null. For instance, when updating an entity values returned from the backend for some fields are `null` (instead of `undefined`) and this registers as invalid when it is not.

### Wanted behaviour

Fields that are nullable should accept `null` value.

### Possible workarounds

A `override` schema can be added that overrides the generated schema with nullable value, but this brings additional confusion with validation.

**Comment by jtomic-croz** [comment]
@nkescec can you give an example where you have to add this workaround?

**Comment by nkescec** [comment]
Lets say we have on backend a field in our creation DTO like this:
```java
private String note;
```

As it is visible from no validations, any value is permitted and that includes null. 

Unfortunately, when this is parsed into a yup validation on the frontend, it is not declared to the validator that this field can be nullable with `.nullable()`. Because of that, frontend validation always fails even when the field is permitted to be null. The example where this most often happens is when an entity has to updated and it has null fields.

The workaround is to use the concatenation of the generated yup schema and override schema that specifically says that that field can be nullable.
